#!/bin/bash

echo "=== Gemini API Setup ==="
echo ""
echo "1. Go to https://aistudio.google.com/"
echo "2. Sign in with your Google account"
echo "3. Click 'Get API Key' in the left sidebar"
echo "4. Create a new API key (it's free)"
echo "5. Copy the API key"
echo ""
echo "Once you have your API key, run:"
echo "export GEMINI_API_KEY=your_actual_api_key_here"
echo ""
echo "To make it permanent, add this line to your ~/.zshrc file:"
echo "echo 'export GEMINI_API_KEY=your_actual_api_key_here' >> ~/.zshrc"
echo ""
echo "Then restart your terminal or run: source ~/.zshrc"
echo ""
echo "After setting the API key, restart the backend server."
